---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: kubia
    annotations:
        haproxy.org/path-rewrite: "/"
spec:
  tls:
  - hosts:
    - foo.example.com
    secretName: tls-secret
  rules:
  - host: foo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubia
          servicePort: 80