apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
    - name: database
      image: mongodb
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      ports:
        - containerPort: 21017
          protocol: TCP
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: database-pvc
